name: daggerc
version: "0.1"
category: Language

dependencies:

library:
  build-tools:

  source-dirs: src
  dependencies:
    - base >= 4.9.1.0
    - mtl
    - parsec
    - text
    - bytestring >= 0.10.8.1
    - containers >= 0.5.7.1
    - cryptonite >= 0.21
    - aeson >= 1.0.2.1
    - split >= 0.2.3.1
    - directory >= 1.3.0.0

executables:
  daggerc: &daggerc
    main: src/Main.hs
    dependencies:
      - daggerc
      - base >= 4.9.1.0
      - aeson >= 1.0.2.1
      - bytestring >= 0.10.8.1
      - split >= 0.2.3.1
      - directory >= 1.3.0.0

tests:
  unit:
    source-dirs: unittests
    main: main_tests.hs
    dependencies:
      - daggerc
      - base >= 4.9.1.0
      - test-framework
      - test-framework-hunit
      - HUnit
      - QuickCheck
      - containers
      - hspec
