flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- .
extra-deps:
- HUnit-1.6.0.0
- aeson-1.3.0.0
- ansi-terminal-0.8.0.2
- ansi-wl-pprint-0.6.8.2
- attoparsec-0.13.2.2
- base-compat-0.9.3
- basement-0.0.7
- call-stack-0.1.0
- colour-2.3.4
- cryptonite-0.25
- dlist-0.8.0.4
- extensible-exceptions-0.1.1.4
- foundation-0.0.20
- hashable-1.2.7.0
- hostname-1.0
- integer-logarithms-1.0.2.1
- memory-0.14.16
- mtl-2.2.2
- old-locale-1.0.0.7
- parsec-3.1.13.0
- primitive-0.6.3.0
- random-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- scientific-0.3.5.3
- split-0.2.3.3
- tagged-0.8.5
- test-framework-0.8.2.0
- test-framework-hunit-0.3.0.2
- text-1.2.3.0
- th-abstraction-0.2.6.0
- time-locale-compat-0.1.1.3
- transformers-compat-0.6.1.5
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vector-0.12.0.1
- xml-1.3.14
resolver: ghc-8.0.2
